# Generated by Django 3.2.3 on 2021-07-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default='0001-00-00 00:00:00'),
        ),
    ]
